# Generated by Django 4.2 on 2024-10-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('gestion_comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichierIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.fichier')),
            ],
        ),
        migrations.CreateModel(
            name='TypeIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_incident_icon', to='common.fichier')),
                ('type_autorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_incidents', to='gestion_comptes.typeautorite')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_incident', models.DateTimeField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_TRAITEMENT', 'En traitement'), ('TRAITE', 'Traité'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('autorite_en_charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_en_charge', to='gestion_comptes.autoritecompetente')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='gestion_comptes.commune')),
                ('fichiers', models.ManyToManyField(related_name='incidents', through='gestion_incidents.FichierIncident', to='common.fichier')),
                ('localisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.localisation')),
                ('signaleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents_signales', to='gestion_comptes.personne')),
                ('type_incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_incidents.typeincident')),
            ],
        ),
        migrations.AddField(
            model_name='fichierincident',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichier_incidents', to='gestion_incidents.incident'),
        ),
    ]
